### ISSUE TITLE
Make translations possible

### ISSUE THREAD

**Issue by cweiske** [calcitem/Sanmill#202]
I would like to translate the UI into German so that my kids can use the game.
Currently it seems that only the game title can be translated for Android, but nothing else.

It would be nice if you could add a way for others to translate the UI.

**Comment by calcitem** [comment]
We are happy to see that children will benefit from this free App!

We also sincerely hope that volunteers can help us translate into various languages including German!

For translation method, please refer to https://github.com/calcitem/Sanmill/wiki/How-to-translate

Thanks a lot!

--------------------

Wir freuen uns, dass Kinder von dieser kostenlosen App profitieren werden!

Wir hoffen auch aufrichtig, dass Freiwillige uns helfen können, in verschiedene Sprachen einschließlich Deutsch zu übersetzen!

Informationen zur Übersetzungsmethode finden Sie unter https://github.com/calcitem/Sanmill/wiki/How-to-translate

Vielen Dank!

**Comment by cweiske** [comment]
Thank you for the quick reply!

**Comment by calcitem** [comment]
Just a quick one!
I will fetch your MR and test it asap!

**Comment by calcitem** [comment]
Fixed "Move list":
https://github.com/calcitem/Sanmill/commit/74d7224263d04ce97198276d6844f32ae19aadb1

**Comment by calcitem** [comment]
در حال حاضر ترجمه فارسی رابط کاربری رابط کاربری در حال انجام است. از آنجا که هیچ توسعه دهنده ای با زبان فارسی آشنا نیستیم ، ما عمدتا از ترجمه ماشینی استفاده می کنیم. بنابراین ، ما داوطلبین را که در بررسی دستور زبان به ما کمک می کنند ، گرمی می پذیریم. متشکرم!
