### ISSUE TITLE
ساعدنا في الترجمة Want to help translate Sanmill? 

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#231]
Those interested in lending a hand for their completion or for improving existing translations are encouraged to contribute via https://poeditor.com/join/project?hash=DStQiKAsPb

Would you please click on the language you want to proofread and directly modify the corresponding entry to participate in translation proofreading? After completion, you can click "Notify Contributors" or leave a message here to inform us that we will apply the updated translation to the App. If you have any questions about the purpose of the original entry, you can add a comment, and we will get back to you!

**Comment by iJahangard** [comment]
I have problem with thet website for translation
It is confusing to me?

What should I exactly do?

**Comment by iJahangard** [comment]
> چگونه به ما در ترجمه کمک کنیم
> 
It should be like :
به ما در ترجمه کمک کنید!

**Comment by calcitem** [comment]
Welcome to join our translation project!

You can log in to the website, select Persian translation, modify the translation, and submit. We will check the translation results and apply them to the App to recompile.
 
At present, all entries in Persian are machine translation, without manual proofreading, polishing and modification.  

In addition, the Persian translation is based on English, not Chinese.  Haha.

**Comment by iJahangard** [comment]
I did some editions
You can see them in that site ! Right?

**Comment by calcitem** [comment]
Thanks a lot!  Tonight I will export as an arb file and compare it with the arb file in the repository to confirm whether the modification takes effect.  

By the way, it’s the first time I use this website, and I need to explore it.  And you are the first contributor to contribute translations through this website!

**Comment by calcitem** [comment]
It looks like it works, because I just received an email notification with the following content:

Hi Calcitem,

A new comment from امیر has just been posted in Sanmill, Persian language on the term:

moves

امیر says:
Please make this like:
حرکت nاُم

**Comment by iJahangard** [comment]
> 
> It looks like it works, because I just received an email notification with the following content:
>
  Great!!
> Please make this like:
> حرکت nاُم
> 
Actually like this ![IMG_۲۰۲۱۰۶۳۰_۱۶۲۷۰۷.jpg](https://user-images.githubusercontent.com/67248292/123956547-0b367a80-d9c0-11eb-80c5-bf20a5013c25.jpg)
The transition website and github show all content from left to right so i send an screenshot of a correct appearance

But that sentence is correct you can copy paste it and it will have no problem

I requested you for a problem with custom values ,i mean that ⎵ character
How can I manage it to where I want , not just in the beginning of sentence?

**Comment by calcitem** [comment]
> I did some editions
> You can see them in that site ! Right?

After exporting the arb file at https://poeditor.com/projects/export_language?id=453149&id_language=126, and the file in the repository https://github.com/calcitem/Sanmill /blob/master/src/ui/flutter_app/lib/l10n/intl_fa.arb I can see the difference between the changes generated and it works fine!

**Comment by iJahangard** [comment]
So I just do translate and tell you after big changes right? Then you add them to app's strings, right?

**Comment by calcitem** [comment]
Yes, you can continue to fix the rest of the Farsi translation on the translation site, and when it's done, you can reply to it here. I will export the arb file on the site, commit it to the Git repository, Push, then compile the apk file, send out the download link (which will be at https://github.com/calcitem/Sanmill/actions), you can download and install it, check the result, and if it is confirmed, reply again, and I will submit it to Google Play Store!

**Comment by iJahangard** [comment]
> I requested you for a problem with custom values ,i mean that ⎵ character
> How can I manage it to where I want , not just in the beginning of sentence?
>
What should i do with this?

**Comment by calcitem** [comment]
The space you mentioned is shown in the location indicated by the arrow in the image below. Do you mean you want to change this space to a different location?

I am considering removing this space from the string instead of adding it to the code to avoid confusion.

If the effect is not what you expect, you can fix it separately. You don't need to get every translation entry correct at once. After all, we can continue to fix it later by looking at the recompiled app's GUI.

![Screenshot_۲۰۲۱۰۶۳۰-۲۳۴۳۵۸](https://user-images.githubusercontent.com/51521682/123991464-53c05900-d9fd-11eb-968a-99aa51fae361.png)

**Comment by iJahangard** [comment]
> The space you mentioned is shown in the location indicated by the arrow in the image below. Do you mean you want to change this space to a different location?
> 
Ugh ! It was an space ? I thought it is the Variable position (where the numbers are)

> I am considering removing this space from the string instead of adding it to the code to avoid confusion.
>
 I didn't mean that
> If the effect is not what you expect, you can fix it separately.
> 
Effect of what? In the screenshot ? If yes ,it is fine
> You don't need to get every translation entry correct at once. After all, we can continue to fix it later by looking at the recompiled app's GUI.
>
I agree ! Should I leave comment for those strings? Or not, let's what destiny is! ｡◕‿◕｡

**Comment by calcitem** [comment]
> Effect of what? In the screenshot? If yes, it is fine

I mean all the effects of App GUI, including the screenshot above.

> I agree! Should I leave a comment for those strings? Or not, let's what destiny is! 

My native language is Chinese, and I'm actually not sure about the accuracy of my English translations. Maybe the original English translation makes people confused instead. If you have questions about the translation entries, you can leave a comment on the translation website and I can receive an email notification and reply.

**Comment by iJahangard** [comment]
> I mean all the effects of App GUI, including the screenshot above.
> 
So we will decide later

> My native language is Chinese, and I'm actually not sure about the accuracy of my English translations. Maybe the original English translation makes people confused instead. If you have questions about the translation entries, you can leave a comment on the translation website and I can receive an email notification and reply.
> 
Okay fine

**Comment by justinacolmena** [comment]
Finnish translation:

Human against computer = "Ihminen tekoälyä vastaan"
Human against human = "Ihminen ihmistä vastaan"

**Comment by calcitem** [comment]
> Finnish translation:
> 
> Human against computer = "Ihminen tekoälyä vastaan"
> Human against human = "Ihminen ihmistä vastaan"

Thanks!

Could you join https://poeditor.com/projects/po_edit?id_language=49&per_page=20&id=453149

**Comment by calcitem** [comment]
We use weblate to translate now.
