### ISSUE TITLE
gcc, clang compiler warnings

### ISSUE THREAD

**Issue by flexoron** [calcitem/Sanmill#255]
Hello,
maybe warning cleanup is a good idea occasionally.

Compiling src for linux(uci): 
gcc version 11.1.0 
clang version 12.0.1

(gcc,clang) 2 Warnings:

1.) Harmless
mills.cpp: In function ‘Depth Mills::get_search_depth(const Position*)’:
mills.cpp:487:42: warning: cast from type ‘const Position*’ to type ‘Position*’ casts away qualifiers [-Wcast-qual]
  487 | is_star_squares_full((Position *)pos)) {

Fix: mills.cpp
  487 is_star_squares_full(const_cast<Position *>(pos))) {

2.) **Not sure whether this is programmed for checking or other purposes?**
search.cpp: In function ‘Value search(Position*, Sanmill::Stack<Position>&, Depth, Depth, Value, Value, Move&)’:
search.cpp:222:29: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
  222 | if (pos->rule50_count() > rule.nMoveRule) {

Fix: position.h 
   39 size_t rule50 {0};
   97 size_t rule50_count() const;
  257 inline size_t Position::rule50_count() const

**Comment by calcitem** [comment]
Hello, the compilation warning problem has been fixed. 

Rule50 cannot be a negative number. 

 
Thank you for the solution! 

I am surprised that you are familiar with C++, your GitHub project does not have a cpp project.
