### ISSUE TITLE
Wrong arow side - rtl

### ISSUE THREAD

**Issue by islam2hamy** [calcitem/Sanmill#281]
<a href="https://ibb.co/jRLDBT7"><img src="https://i.ibb.co/Wtcfq6S/5dedaf5a-a73c-41dc-a9be-21bb134f1841.jpg" alt="5dedaf5a-a73c-41dc-a9be-21bb134f1841" border="0"></a>

It is my turn , not the AI

**Comment by calcitem** [comment]
Thanks a lot!!

New apk: https://github.com/calcitem/Sanmill/actions/runs/1272809335
