### ISSUE TITLE
The color of the status bar icon changes when page switching

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#345]
When the app is first opened, the color of the icon in the status bar is black. After entering the settings page, the icon turns white, and then back to the game page, the icon remains white. Is there any way to unify it into white?

The problem can be reproduced on the pixel phone. This problem does not exist in some mobile phones.

Maybe https://github.com/FooStudio/flutter_statusbar_manager is useful.

**Comment by Leptopoda** [comment]
now that we use an appBar on the gamePage this might be fixed. I've experienced this before but it isn't present on the latest dev (or AppTheme_migration)

can you confirm?

**Comment by calcitem** [comment]
I have uploaded:
https://github.com/calcitem/Sanmill/actions/runs/1402768548
to Google Play Console:
https://play.google.com/console/u/1/developers/4614143494034576766/app/4973110067016548319/pre-launch-report/details?artifactId=4859615124677821355&tab=accessibility

We can see the result in one hour.

**Comment by calcitem** [comment]
Wondelful! Fixed!
