### ISSUE TITLE
The locale zh is not supported, falling back to englisch translations

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#357]
When the app starts, it will print an exception log, prompting that `zh` is not supported. But it seems to have no effect.

There is a spelling error in the log `Englisch`. It looks like this log was written by a German programmer, haha.

```
I/flutter (24250): [2021-10-30 12:25:50.468252 | Catcher | WARNING] Screenshots path is empty. Screenshots won't work.
I/flutter (24250): [2021-10-30 12:25:50.477356 | Catcher | FINE] Catcher configured successfully.
D/DecorView[](24250): getWindowModeFromSystem  windowmode is 1
I/flutter (24250): Set Special Country and Region to .
I/flutter (24250): The locale zh is not supported, falling back to englisch translations
I/flutter (24250): [game_page] Engine type: EngineType.humanVsAi
```

**Comment by Leptopoda** [comment]
why did you merge dev into master??
we clearly still have some bugs. 

Can I just revert the merge and we can hold off until the bugs are fixed??

**Comment by Leptopoda** [comment]
this is caused by better feedback not supporting `zh` I opend a [PR](https://github.com/ueman/feedback/pull/132) fixing the typo in the log

better feedback does support providing custom language delegates and we should look into utilizing them for the missing languages.
There might also be some other not supported languages and we should probably check everyone :upside_down_face:

**Comment by calcitem** [comment]
The Better Feedback called by this app was forked by me. I don’t know why there is this warning log. I have added a lot of languages.

https://github.com/calcitem/feedback

**Comment by Leptopoda** [comment]
I just removed the need for the fork as I wanted to make the implementation cleaner.

I'll cleanly fix the problems later (without needing to depend on the fork).

**Comment by calcitem** [comment]
Thanks a lot! I didn't notice that this commit changed the dependency.

https://github.com/calcitem/Sanmill/commit/2e48f98f2ad57bfada123c0160d8da6c9d7e677b#diff-3d9d6baaeaa8d12b565ee62d3069e36d1bff4fc003dc10c9a07196d572f9ef35
