### ISSUE TITLE
nicht mehr spielbar

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#366]
A blind friend's feedback

sagt nichts mehr an. handelt, schlepend, verlangsammt. zusammenbruch. nicht mehr spielbar.

vor 1.1.38, ist besser für screenreader USW. 

hallo, - es tut mir leid, aber die neuste, version, ist nicht zu gebrauchen für blinde. fehlerhafte, reaktionen. danke für ihre gedulld, und für ihr interesse. - grüße, aus österreich. 

branch: dev 
build: 576
link: https://github.com/calcitem/Sanmill/actions/runs/1402768548

**Comment by Leptopoda** [comment]
What exactly is wrong?
Where are the problems?

**Comment by calcitem** [comment]
#329 exists from beginning to end, and it shouldn't affect it.

 This blind friend is inconvenient to type. I am asking him to try to record the problem on the screen and add voice to describe the problem, and send it to me to see what is going on. I may need to trouble you to translate his German at that time.  Ha ha.

**Comment by calcitem** [comment]
Today I uploaded the latest version buld #588 to the internal test channel, and I will ask this user to try again to see if the problem can be reproduced.

I asked him to return to the official version, but he didn't succeed in a long time. He said that there is a problem with the firewall. I didn't understand it. So just ask him to continue to wait new version to upgrade.

**Comment by calcitem** [comment]
Fixed.

8b697a96efdc0519800ed4edc840949c93307f9f
c315a75a12ac313524c3164bf144e935b48e4fbc
720befc41d70ada72c4a064ee22dc9e9300a4329
750ee76460d5252e5b955ec6930908de0eab0b04
76812eeb8dbe56698d3193982b90fea44e86b1e9
b03c77657c1f5f4ceefb4abaf6ae46081745862c
9a35041b28a751bc40639f68ba2ba6d1def8212d
a52b51e5c3d0b0267bf8bb97393ede8431197647
