### ISSUE TITLE
Automatically modify the version number when building with IDE

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#367]
Is there any way to allow users to automatically modify the version number and add a Git revision to the locally compiled version? 

Some users reported that the 2196 version is abnormal. In fact, the current locally compiled version is this version number, which is indistinguishable.

On the other hand, it is true that the update of the branch master needs to be more cautious. Unexpectedly, there are still many users who compile the app themselves, and they can't even wait for the compilation of CI.

**Comment by Leptopoda** [comment]
> On the other hand, it is true that the update of the branch master needs to be more cautious.

Told ya 🙃

Why would you need a way to add local tags? I'd say we could iterate the build number for every PR like `1.38.0-x`. 
And as mentioned above we should only push to master when ready (dev isn't bad at all)

**Comment by calcitem** [comment]
CI systems such as GitHub action will auto add PR. I don't know how to add it automatically when compiling locally.

**Comment by Leptopoda** [comment]
I don't understand what you mean :(

**Comment by calcitem** [comment]
Tap `About -> Version Info`. We can see the Git commit id.

Although the apk is built locally using the IDE rather than through CI,  the Git revision can also be displayed.

**Comment by Leptopoda** [comment]
Do we really need the git tag in production?

Isn't the version code enough?

I think a strategy where we only push to master when it's really ready and then put up a new release would also fix that.

I think we should also enable this on dev only (using the compile configs).

**Comment by calcitem** [comment]
OK
