### ISSUE TITLE
The drawer does not respond to the upward swipe gesture

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#388]
**Describe the bug**
The drawer does not respond to the upward swipe gesture.

**Expected behavior**
The drawer can respond to the upward swipe gesture so that even a small screen (such as Nokia 1) can also display the "About" menu item by swiping. However, the "About" menu item cannot be displayed now.

**Screenshots**
![Screenshot_20211110-000542 - Copy](https://user-images.githubusercontent.com/51521682/140964751-a361233d-a026-4fe8-aafb-bc4b6a770d21.png)

**Smartphone (please complete the following information):**
 - Device: Nokia 1
 - OS: Android Go

**Additional context**
https://github.com/calcitem/Sanmill/actions/runs/1436304832

**Comment by Leptopoda** [comment]
bruh :woman_facepalming: 

I'll fix that xD

**Comment by Leptopoda** [comment]
Ok having a quick look I already

**Comment by Leptopoda** [comment]
@calcitem I can't find a feasable solution to this. For now the easiest thing would be to let the swipe gesture (to return the drawer) only take palce on the open screen view. Similar to how i had it in the initial drawer rewrite. Is there something against this?

**Comment by calcitem** [comment]
Sorry, I did not understand what you mean.  

According to my understanding, if this problem is difficult to solve, we can consider hiding something on the small screen phone, such as the title.

**Comment by calcitem** [comment]
Fixed by:
12d1f6d2ee0c7dd3d01d814a61293fc46d568089
42f67ab997068367318da3e390781bed99017f9f
60c52edcc759d200a5939dc35f86968558645d5d
