### ISSUE TITLE
Feedback translations [Help Wanted]

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#398]
Some comments about this app are still difficult to understand after translation. I don't know how to reply, so I collected them here.  It would be great if everyone could help translate and explain.

**Comment by calcitem** [comment]
Greek:

ερόσυνο.

**Comment by Leptopoda** [comment]
This string isn't currently used in our app. 
Also I don't know what the heck this means ...

**Comment by calcitem** [comment]
This is a user’s comment on the Play Store, not a string used by the app.

**Comment by Leptopoda** [comment]
Ok I had a look at the play console and you somehow missed a few letters while pasting it here. 
The text in question is "Ευφρόσυνο" wich means something like "euphoric", "enthusiastic" or "to be happy".
Together with the five star rating I guess they wanted to express their feelings with the app.

**Comment by calcitem** [comment]
Ευφρόσυνο - Even this word can't be translated on my phone, I don't know it is a new buzzword. 😂😄

**Comment by Leptopoda** [comment]
It isn't a new buzz word but you're right it is strange that it can't be translated by various tools

**Comment by calcitem** [comment]
Thanks!
