### ISSUE TITLE
Reactive font scaling

### ISSUE THREAD

**Issue by Leptopoda** [calcitem/Sanmill#400]
If we adjust the font size in the configuration, the font does not change.
_Originally posted by @calcitem in https://github.com/calcitem/Sanmill/issues/350#issuecomment-965419631_

Ok The font scaling isn't adaptive, does only apply to `Text` widgets. We should search a way to set the global scale factor `MediaQuery.of(context).textScaleFactor` in the app. 

EDIT:
```dart
ThemeData(
  child: MediaQuery(
    child: widget as Widget,
    data: MediaQuery.of(context).copyWith(textScaleFactor:1.0),
    ),
)
```
[source](https://stackoverflow.com/questions/57337154/how-to-set-mediaquery-textscalefactor-of-fontsize-in-materialapp-theme)

**Comment by Leptopoda** [comment]
Hi @calcitem,
I've made a commit introducing the desired feature (and I think it turned out quite clean)

Please have a test of the fonts. There might bee some texts with wrong fonts so please let me know which they are and how big the font should be.

The following table taken from the [TextTheme](https://api.flutter.dev/flutter/material/TextTheme-class.html) class also explains what TextStyle of the current TextTheme it correlates to. Please have a thorough read of the provided resource and maybe also consult the [material design spec](https://material.io/design/typography).

```
NAME         SIZE  WEIGHT  SPACING
headline1    96.0  light   -1.5
headline2    60.0  light   -0.5
headline3    48.0  regular  0.0
headline4    34.0  regular  0.25
headline5    24.0  regular  0.0
headline6    20.0  medium   0.15
subtitle1    16.0  regular  0.15
subtitle2    14.0  medium   0.1
body1        16.0  regular  0.5   (bodyText1)
body2        14.0  regular  0.25  (bodyText2)
button       14.0  medium   1.25
caption      12.0  regular  0.4
overline     10.0  regular  1.5
```

If you find anything that's off please let me know where and also which of the above mentioned TextStyles to use. We shouldn't use any size besides the given ones. Also the board notations don't scale. Is this intended?

**Comment by calcitem** [comment]
Cool! 

Need to ensure that switching to any language will not crash under the largest font.  At present, after adjusting to the maximum zoom, switching to Persian will crash.

The font of the menu on the left needs to be relatively large, and the text explanation of the configuration items needs to be smaller.  I can adjust this tomorrow.

**Comment by Leptopoda** [comment]
We should use the values as specified in the material design guideline. There already where some overflows in the previous version and we'll need to address them separately. I don't think that deviating from the norm just to fix our mistakes isn't the right way.

**Comment by calcitem** [comment]
OK. I will try.

**Comment by Leptopoda** [comment]
Any news on this?
Can this be marked as done and further changes are going to be made separately?

**Comment by calcitem** [comment]
No problem. I'll make a new commit for issues where there is a difference between the relative font size and the original.
