### ISSUE TITLE
The toolbar icon should not change when switching to RTL layout

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#406]
The game toolbar and navigation toolbar's icons should not change when switching to the RTL layout. But now it changed.

See:
https://github.com/calcitem/Sanmill/issues/241
Commit 9fb44f204f45af8188b39c247a581e06c8e2cc88

Git tag v1.1.38 does not have this problem.

Thanks!

**Comment by Leptopoda** [comment]
I'll have a look

**Comment by Leptopoda** [comment]
fixed !

**Comment by calcitem** [comment]
Game toolbar has been fixed.
Nav toolbar has not been fixed.
Expect same with LTR.

**Comment by Leptopoda** [comment]
interesting ... I'll have a look later

**Comment by Leptopoda** [comment]
ok I fixed it and it's based on #370 when that's done I'll upload it.

**Comment by calcitem** [comment]
Verified. It is OK now.
