### ISSUE TITLE
Drawer Icon missplacement in LTR

### ISSUE THREAD

**Issue by Leptopoda** [calcitem/Sanmill#407]
for me this seems to be an issue in the flutter framework.
I'll report it over there and we'll see.

I might add a temporary fix for now.

EDIT: There already is an open issue with a pending PR
https://github.com/flutter/flutter/issues/60521

EDIT 2:
let's merge this PR to move forward. I'll address a temporary fix separately

_Originally posted by @Leptopoda in https://github.com/calcitem/Sanmill/pull/350#issuecomment-976303436_

**Comment by calcitem** [comment]
OK!。Go ahead.

**Comment by calcitem** [comment]
This bug does not exist on Flutter 3.3.
