### ISSUE TITLE
The translation is mess

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#420]
I am thinking to revert the modification of English arb first. At present in master branch, German and Persian have been translated, but no volunteers can be found in a short time to modify the translation to adapt to the new changes of branch dev. Maybe you can help in German, but the downloads account for 59% Of Iran is currently no one can handle in short time.

**Comment by calcitem** [comment]
I will try to translate it. I now set Play Store to download the Beta version in Iran and Germany to avoid negative ratings.

**Comment by Leptopoda** [comment]
Wie might indeed wanna think about switching translation platforms. Some (if not most) include computer generated translation (Google translator...) and some even include a translation cache where small changes wouldn't result in rewriting everything.

**Comment by calcitem** [comment]
OK. Just take this opportunity to modify the variables of the translation entry thoroughly.

**Comment by Leptopoda** [comment]
I think this can be closed now that you migrated everything to weblate

**Comment by calcitem** [comment]
Close.

See https://github.com/calcitem/Sanmill/pull/465
