### ISSUE TITLE
LateInitializationError: Field '_drawSoundId@82306828' has already been initialized.

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#424]
**Describe the bug**

LateInitializationError: Field '_drawSoundId@82306828' has already been initialized.

branch: dev

**To Reproduce**

1. Debug 'main.dart' (Hot Reload)
2. Exception:

```
LateError._throwFieldAlreadyInitialized (internal_patch.dart:211)
Audios._drawSoundId (audios.dart:47)
Audios.loadSounds (audios.dart:72)
<asynchronous gap>
```

```dart
class Audios {
  const Audios._();
  //static AudioPlayer? _player;
  static final Soundpool _soundpool = Soundpool.fromOptions();
  static bool _initialized = false;
  static int _alarmSoundStreamId = 0;
  static late final int _drawSoundId;    // Exception
  static late final int _flySoundId;
  static late final int _goSoundId;
  static late final int _illegalSoundId;
  static late final int _loseSoundId;
  static late final int _millSoundId;
  static late final int _placeSoundId;
  static late final int _removeSoundId;
  static late final int _selectSoundId;
  static late final int _winSoundId;
  static bool isTemporaryMute = false;
```

Thanks!

**Comment by Leptopoda** [comment]
is this reproducible?
I don't get this error and can't think of why this should occur.

**Comment by calcitem** [comment]
Branch dev has this issue. The recurrence probability is 70%.  Appears when clicking the IDE debug button to start the app.

**Comment by Leptopoda** [comment]
The problem is independent from the windows support

I don't get the error but I'll see what I can do.

**Comment by calcitem** [comment]
I am currently not sure that it can solve the problem that the stoping audio function of Windows is not implemented. If the Audio package cannot be replaced, I will look at this problem again and please help.  So I first assign this bug to myself.

**Comment by calcitem** [comment]
It looks like it is already fixed. (Commit 71248fc8)
