### ISSUE TITLE
The board is not clean when starting a new game if AI is player 1

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#452]
**Describe the bug**

The pieces on the board are not clear when starting a new game.

**To Reproduce**
1. Click on the `Options` button on the toolbar.
2. Click on `First move -> Human`
3. Click on `Back` on the left-top.
4. Click on `d2`.
5. Click on `Game -> New game`
6. The board is not clean.

**Expected behavior**
The board is clean.

**Comment by Leptopoda** [comment]
Reseting the game has been revamped. This should be fixed now.

The AI moving first is still not implemented but the board should be clean nevertheless.

**Comment by calcitem** [comment]
Thanks! I expect to verify it tomorrow. 

BTW. Today I found a severe bug in the AI that would cause the moving phase to be weaker than expected. Therefore, I must release version 1.1.39 on the branch master today urgently.

**Comment by Leptopoda** [comment]
I would not do that as you merged some unstable changes into master a while ago.

I'm not sure if it is stable. You should make a separate commit based on the last tag.

**Comment by calcitem** [comment]
I rolled back branch master to the most recent tag a long time ago. So no problem.

**Comment by calcitem** [comment]
Verify result:

The board is clean when starting a new game if AI is player 1.
But the AI didn't start placing a piece. This can be considered another bug.
