### ISSUE TITLE
Change the rule when switching language to Persian

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#468]
**Describe the bug**
Change the rule when switching language to Persian.

**To Reproduce**
1. Uninstall apk
2. Install apk
3. Run app
4. Play a game
5. switching language to Persian
6. See the rule is changed.

**Expected behavior**
Do not change the rule.

**Comment by Leptopoda** [comment]
I've changed how we handle the different rules.

I don't think that the rules should be changed by changing the locale. I think that this is a fairly unexpected behavior.
I think rules should be set once and then it's up to the user to customize them. The display language shouldn't affect this separate setting.

Nevertheless with the way I implemented it now it'll be way easier to introduce other settings or even change them dynamically based on the rules (if that is desired).

**Comment by calcitem** [comment]
For reasons why you need to set default rules for some particular countries, see:

https://github.com/calcitem/Sanmill/issues/224#issuecomment-877720875

Downloads in Iran account for 60% of the total downloads, so we must pay attention to Iranian users. After communicating with Iranian users, I learned that there is no market for 9 men in Iran at all, and Iranians play 12 men, so there is no need for Iranian users to choose the mill rules when they start the game for the first time. In addition, after the default rule adjustment for Iran, there was a surge in daily downloads, which can be seen by looking at the Google Play Console background data.

**Comment by calcitem** [comment]
Also, there are subtle differences in the rules of different countries, such as China, Iran, South Africa, etc., and it is not enough to simply provide 12 or 9 men's morris options. For example, China, Iran, and South Africa all use 12 men, but there are a lot of subtle rule differences.

**Comment by calcitem** [comment]
The default rules are only set based on the system language on the FIRST launch, and when the user changes the display language in the app later, the rules SHOULD NOT be automatically modified.

**Comment by Leptopoda** [comment]
> so there is no need for Iranian users to choose the mill rules when they start the game for the first time. 

I didn't do anything like that.

> The default rules are only auto-set based on the system language on the FIRST install and launch, and when the user changes the display language in the app later, the rules SHOULD NOT be automatically modified.

That's exactly what I've done. Is this ok or not?

**Comment by calcitem** [comment]
Yes!

**Comment by Leptopoda** [comment]
So can this be closed now?

**Comment by calcitem** [comment]
Yes.

**Comment by calcitem** [comment]
I cannot verify it because the app will show a grey screen when switching language.
