### ISSUE TITLE
Adjust font size

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#483]
When https://github.com/calcitem/Sanmill/issues/400 is applied. We need to adjust font scaling for each element.

**Comment by Leptopoda** [comment]
what do you mean by that?

**Comment by calcitem** [comment]
The font size of some elements changes relatively and requires fine-tuning.  Fine tuning does not modify the original overriding mechanism.

**Comment by calcitem** [comment]
Done.
