### ISSUE TITLE
Need to draw notation after the board line is drawn

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#484]
It is best to draw notation after the board line is drawn, not to overwrite it after adjusting it to a significant value.

**Comment by Leptopoda** [comment]
This won't change anything.

Also as said in #350 we should not add workarounds for things we can fix properly. In this case we should adjust the position of the lines so the two paths wont clip :upside_down_face:

**Comment by calcitem** [comment]
This problem is not reproduced in the latest version.
