### ISSUE TITLE
XXXSettingsKey are all "settings"

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#583]
These keys are all set to "settings", is there any problem?

`database.dart`

```dart
  /// Key at which the [RuleSettings] will be saved in the [_ruleSettingsBox]
  static const String ruleSettingsKey = "settings";

  /// Key at which the [DisplaySettings] will be saved in the [_displaySettingsBox]
  static const String displaySettingsKey = "settings";

  /// Key at which the [ColorSettings] will be saved in the [_colorSettingsBox]
  static const String colorSettingsKey = "settings";
```

**Comment by Leptopoda** [comment]
Just having a quick look at 
https://github.com/calcitem/Sanmill/blob/0fd612143e8d9367d1c430707d5aa08e1a8a7f66/src/ui/flutter_app/lib/services/database/database.dart

I think it's ok to be like that. As they are "public" they are probably used elsewhere and I hven't looked deeper.

**Comment by calcitem** [comment]
Thanks!  I tested the latest code, and it seems that there is no problem with the format conversion of the old and new versions and the configuration saving of the new version.
