### ISSUE TITLE
Pikafish AI engine

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#610]
Pikafish AI engine

**Comment by shuangqiao999** [comment]
你好 这个是源于鳕鱼引擎吗？
有个源于鳕鱼的象棋引擎项目(https://github.com/PikaCat-OuO/Pikafish) 有兴趣看一下吗？

**Comment by calcitem** [comment]
> 你好 这个是源于鳕鱼引擎吗？ 有个源于鳕鱼的象棋引擎项目(https://github.com/PikaCat-OuO/Pikafish) 有兴趣看一下吗？

你好！为啥不基于 https://github.com/ianfab/Faity-Stockfish 项目来做呢？基于鳕鱼实现了象棋引擎，已经很成熟了。支持 NNUE。

**Comment by shuangqiao999** [comment]
之前皮卡鱼团队也是基于Fairy-Stockfish
的 后来Fairy-Stockfish
的作者说最好基于stockfish15做 皮卡鱼团队又基于stockfish15做的nnue象棋引擎 现在皮卡鱼最新的发行版 已经甩了fairy-stockfish几条街了 超越了阿尔法猫象棋引擎 皮卡鱼才用分布式跑谱训练

**Comment by shuangqiao999** [comment]
我看到你fork fairy stockfish 如果对中国象棋有兴趣不妨看看皮卡鱼项目

**Comment by calcitem** [comment]
> 我看到你fork fairy stockfish 如果对中国象棋有兴趣不妨看看皮卡鱼项目

看起来这个项目很了不起，不过我理解是工作量主要在于训练网络，似乎其他地方已经很成熟了。不知道那些地方能帮上忙？

另外，我的主要工作是基于 Fairy-Stockfish 开发 Mill 程序，并准备将其推送到 Fairy-Stockfish 评审。

**Comment by shuangqiao999** [comment]
现在皮卡鱼团队需要手机版开发者 之前有商业手机版盗用皮卡鱼引擎和权重 因为皮卡鱼一直秉承开源免费 想把鳕鱼的模式在国内实现

**Comment by calcitem** [comment]
> 现在皮卡鱼团队需要手机版开发者 之前有商业手机版盗用皮卡鱼引擎和权重 因为皮卡鱼一直秉承开源免费 想把鳕鱼的模式在国内实现

这个项目确实很有意义。不过遗憾的是，国内卡游戏版号很严，只能以公司的名义运营。这也就是为啥我只开发面向国外市场的 App 的原因呢。

**Comment by shuangqiao999** [comment]
很遗憾 皮卡鱼团队都是大学生 暂时可能没办法申请游戏版号

**Comment by calcitem** [comment]
> 很遗憾 皮卡鱼团队都是大学生 暂时可能没办法申请游戏版号

商业软件以商业方式使用皮卡鱼并不违反GPL许可，只是不开源的行为违反。可以考虑给这些公司发律师函。

**Comment by shuangqiao999** [comment]
限于都是在读生 没有发律师函 本来有计划开发手机端 一直没遇到手机端开发者 偶然发现有商业手机版用的皮卡鱼引擎和权重 所以想用免费手机版打击商业版的侵权行为 而且这个商业手机版之前用的是fairy stockfish(分析早期版本得知) 的引擎和权重 皮卡鱼出来以后又用皮卡鱼引擎和权重 所以想邀请志同道合的开发者 发行一个免费的手机版

**Comment by calcitem** [comment]
请问 pikafish.nnue 是在哪里下载？

**Comment by shuangqiao999** [comment]
nnue文件只能等开发组发布 没办法下载
