### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [calcitem/Sanmill#752]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5823698161#L1043

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/c6e315dcda1f4defb56d016ae01624051a6e91a8

**Comment by calcitem** [comment]
Thank you for your valuable input and support.

To resolve this issue, I understand that the following modification is required in `metadata/com.calcitem.sanmill.yml`:

- Removal of the line `- src/perfect`.

If it is convenient for you, could you kindly assist with this modification? If your schedule does not permit, I plan to address this change myself within the next three days.

I appreciate your assistance and patience in this matter. Thank you once again for your help and for the critical role you play in maintaining the F-Droid repository.

**Comment by licaon-kter** [comment]
I'll test asap

**Comment by licaon-kter** [comment]
ref: https://gitlab.com/fdroid/fdroiddata/-/commit/43109887f09567106c2f35704436deea3f0e9722

**Comment by calcitem** [comment]
Thanks!!
